CREATE TABLE Post
(
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Author VARCHAR(100) NOT NULL,
    Title VARCHAR(500) NOT NULL,
    Content TEXT NOT NULL,
    DatePosted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);